apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-07-28T07:56:14Z"
  generation: 1
  labels:
    app: app-one
  name: app-one
  namespace: default
  resourceVersion: "617"
  uid: a2398849-b2d2-453e-a9c9-89afa0595f26
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-one
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-one
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/index_template_app1.html
          name: index-template-app1
        - mountPath: /root/script.sh
          name: script-app1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: index-template-app1
        hostPath: 
          path: /vagrant/confs/app1/index_template_app1.html
          type: FileOrCreate
      - name: script-app1
        hostPath: 
          path: /vagrant/confs/app1/script.sh
          type: FileOrCreate
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-28T07:57:21Z"
    lastUpdateTime: "2025-07-28T07:57:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-28T07:56:22Z"
    lastUpdateTime: "2025-07-28T07:57:21Z"
    message: ReplicaSet "app-one-75df98d5d9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
