apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-07-28T07:56:15Z"
  generation: 1
  labels:
    app: app-two
  name: app-two
  namespace: default
  resourceVersion: "632"
  uid: 67890d12-cf4c-4884-a3d5-945db4f48b08
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-two
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-two
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: app-two-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: app-two-volume
        hostPath: 
          path: /vagrant/confs/app2/
          type: Directory
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-07-28T07:57:21Z"
    lastUpdateTime: "2025-07-28T07:57:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-28T07:56:22Z"
    lastUpdateTime: "2025-07-28T07:57:21Z"
    message: ReplicaSet "app-two-7648d46b9f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
