apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-07-28T07:56:15Z"
  generation: 1
  labels:
    app: app-three
  name: app-three
  namespace: default
  resourceVersion: "616"
  uid: 51bd8a9e-c876-439e-82e4-79cae9f48172
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-three
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-three
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: app-three-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: app-three-volume
        hostPath: 
          path: /vagrant/confs/app3/
          type: Directory
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-28T07:57:21Z"
    lastUpdateTime: "2025-07-28T07:57:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-28T07:56:22Z"
    lastUpdateTime: "2025-07-28T07:57:21Z"
    message: ReplicaSet "app-three-bb9bd569" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
